services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Nowo\WalletQrBundle\:
    resource: '../../*'
    exclude:
      - '../../DependencyInjection/'
      - '../../NowoWalletQrBundle.php'
      - '../../QrCode/'
      - '../../Security/'
      - '../../Exception/InvalidWalletQrUrlException.php'

  Nowo\WalletQrBundle\Service\WalletQrService:
    arguments:
      $qrCodeService: '@Nowo\QrCodeBundle\Service\QrCodeService'
      $googleWalletSaveLinkBuilder: '@?nowo_wallet_qr.google_wallet.save_link_builder'
      $appleWalletPassLinkBuilder: '@?nowo_wallet_qr.apple_wallet.pass_link_builder'

  Nowo\WalletQrBundle\Twig\WalletQrExtension:
    tags: ['twig.extension']
